# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#
# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: sample_app

production:
  adapter: postgresql
  encoding: unicode
  user: sample_app
  database: sample_app_production
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test

